### ISSUE TITLE
Migrations for existing users?

### ISSUE THREAD

**Issue by therocode** [mfogel/django-simple-email-confirmation#12]
Hello!

I installed this app to use in my project and it seems to work nicely. However I realised that the users created before the installation of this app return false for .is_confirmed(). This prevents them from logging in. I tried making a data migration for running user.confirm_email(user.confirmation_key) but user.confirmation_key throws an error saying EmailAddress matching query does not exist. Does this mean that the old users entirely lack some database connections to at all be functioning with this app?

How can I properly migrate to mitigate this issue? Thanks!

**Comment by caffodian** [comment]
disclaimer:  not a project member, just a fellow user

Well....users created before you installed the app probably aren't confirmed, are they? :)

But take a look here https://github.com/mfogel/django-simple-email-confirmation/blob/develop/simple_email_confirmation/models.py#L160 for how to create a confirmed email.  

Also take a look at the code that occurs by default to add unverified email https://github.com/mfogel/django-simple-email-confirmation/blob/develop/simple_email_confirmation/models.py#L266 

Likely this wasn't being called before you installed the app, so you don't have the requisite EmailAddress objects to actually call confirm_email on.

**Comment by therocode** [comment]
Thanks for the reply, with the information provided I managed to solve my issue! :)

What I did in my migration was to run that initialising code for users who lacked an email already, and then run the confirmation code. 

(Yep users created before aren't confirmed but they are all known moderators at this point so confirming is a bit redundant)

Thanks again!

**Comment by mfogel** [comment]
Thanks @caffodian for helping out!
