### ISSUE TITLE
deprecated warning in django 1.8

### ISSUE THREAD

**Issue by luisza** [mfogel/django-simple-email-confirmation#13]
RemovedInDjango19Warning: Model class simple_email_confirmation.models.EmailAddress doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.

**Comment by therocode** [comment]
Just to mention, I also get this after upgrading to 1.8

**Comment by mfogel** [comment]
Thanks. Looks like django 1.9 is currently scheduled for release in December - I will address this before then.

**Comment by glynjackson** [comment]
This is supported in Django 1.8 to maintain backwards compatibility I would suggest added something like...

```

try:
    from django.contrib.contenttypes.fields import GenericForeignKey
except ImportError:
    from django.contrib.contenttypes.generic import GenericForeignKey
```

**Comment by g-as** [comment]
This is probably due to the fact that models are imported in the package **__init__.py**. Meaning the model EmailAddress is imported before apps/django reach ready state.

**Comment by g-as** [comment]
Maybe change import style (a.k.a remove imports from **__init__.py**) as per what they did in [django-reversion](https://github.com/etianen/django-reversion/blob/master/CHANGELOG.md#110---02122015)

**Comment by g-as** [comment]
And yes that would be a breaking change.

**Comment by mdamien** [comment]
Small head-up, it's been two months since 1.9 is out and the PR from @AGASS007 is backward-compatible and for now the lib is not working on 1.9. Just sayin' :smile_cat:

**Comment by yeralin** [comment]
+1 I'll try to fork it, and make it compatible 1.9. But not sure, will see

**Comment by omarkhan** [comment]
There are several open pull requests that fix this issue, @mfogel do you know if/when any of them will be merged?

**Comment by yeralin** [comment]
@omarkhan Seems like his account is not active

**Comment by motatoes** [comment]
Any updates on this PR?

**Comment by luisza** [comment]
I think  PR #21 and 

try:
    from django.contrib.contenttypes.fields import GenericForeignKey
except ImportError:
    from django.contrib.contenttypes.generic import GenericForeignKey

Solve the problem.

**Comment by mfogel** [comment]
Hi folks, I'm going to stop maintaining django-simple-email-confirmation (I've been awol for the last year or so anyway, obviously). If any of you would like to take over the task, I will transfer ownership of the pypi registration for the package over to you... and you can take it from there.

I'll be posting the same notice on the main README for this package.

If you're interested, please shoot me an email. My email addr is listed on my public github profile. Cheers.

**Comment by glynjackson** [comment]
@mfogel That is such a shame! I'm sure I don't speak for myself when I say thank you for creating this package and the hard work. It's saved me countless hours by not having to redevelop it. Again, thanks.

**Comment by mdamien** [comment]
I've discussed with @mfogel and I'm gonna transfer the ownership to the Jazzband organization and merge PR #21 in a 2.0 version.

**Comment by glynjackson** [comment]
@mdamien Cool, please post links for reference to the new repo :)

**Comment by motatoes** [comment]
@mdamien Awesome! Please keep us updated with the new repo links

**Comment by mfogel** [comment]
I've added @mdamien as an owner on PYPI and I believe he will handle the transfer from here. Once the new repo is all up and running I'll update this one with links to the new master. Thanks @mdamien for stepping up and volunteering.

Thanks for your patience folks, I'm happy and glad to see the community adopting this project. My apologies for not being on top of it as much as would have been good over the last year or two, but hopefully moving forward the community can do a better job maintaining it than I have. Onward and upward!

**Comment by luisza** [comment]
Hi, 
I think is great new effort could help to growth up this project,  Thank you @mfogel  for your work.
I was thinking in new features like a generic views for registration so Please keep us updated with the new repo links :).

**Comment by mdamien** [comment]
Hi everybody, version `0.20` was just released on pypi with the PR #21 included (django 1.9 and 1.10 support). Support for django 1.7 was dropped, so be careful.

For now, the link to the repo stays the same, while waiting for Jazzband response :+1:

**Comment by luisza** [comment]
Hi, you don't upload the file for 0.20, version exists in pypi (https://pypi.python.org/pypi/django-simple-email-confirmation/0.20) but there is no file associated with this version.
please use 

```
 python setup.py sdist upload
```

or more elaborated 

```
python setup.py sdist bdist_wininst upload
```

I checked in clean virtualenv and this is the result:

> Could not find a version that satisfies the requirement django-simple-email-confirmation==0.20 (from versions: 0.9, 0.9.1, 0.10, 0.10.1, 0.10.2, 0.11, 0.12)
> No matching distribution found for django-simple-email-confirmation==0.20

**Comment by mdamien** [comment]
@luisza thanks, this has been reported in #25 Looks like the problem was that I removed a previous upload for `0.20` (where I had a syntax error in the README) and now I need to release a new version (0.21) to be able to release new files.

Here's the output of `sdist upload` for reference:

```
django-simple-email-confirmation)  python setup.py sdist upload
running sdist
running egg_info
writing requirements to django_simple_email_confirmation.egg-info/requires.txt
writing django_simple_email_confirmation.egg-info/PKG-INFO
writing top-level names to django_simple_email_confirmation.egg-info/top_level.txt
writing dependency_links to django_simple_email_confirmation.egg-info/dependency_links.txt
reading manifest file 'django_simple_email_confirmation.egg-info/SOURCES.txt'
writing manifest file 'django_simple_email_confirmation.egg-info/SOURCES.txt'
running check
creating django-simple-email-confirmation-0.20
creating django-simple-email-confirmation-0.20/django_simple_email_confirmation.egg-info
creating django-simple-email-confirmation-0.20/simple_email_confirmation
creating django-simple-email-confirmation-0.20/simple_email_confirmation/migrations
creating django-simple-email-confirmation-0.20/simple_email_confirmation/south_migrations
creating django-simple-email-confirmation-0.20/simple_email_confirmation/tests
creating django-simple-email-confirmation-0.20/simple_email_confirmation/tests/myproject
creating django-simple-email-confirmation-0.20/simple_email_confirmation/tests/myproject/myapp
copying files to django-simple-email-confirmation-0.20...
copying README.rst -> django-simple-email-confirmation-0.20
copying setup.py -> django-simple-email-confirmation-0.20
copying django_simple_email_confirmation.egg-info/PKG-INFO -> django-simple-email-confirmation-0.20/django_simple_email_confirmation.egg-info
copying django_simple_email_confirmation.egg-info/SOURCES.txt -> django-simple-email-confirmation-0.20/django_simple_email_confirmation.egg-info
copying django_simple_email_confirmation.egg-info/dependency_links.txt -> django-simple-email-confirmation-0.20/django_simple_email_confirmation.egg-info
copying django_simple_email_confirmation.egg-info/requires.txt -> django-simple-email-confirmation-0.20/django_simple_email_confirmation.egg-info
copying django_simple_email_confirmation.egg-info/top_level.txt -> django-simple-email-confirmation-0.20/django_simple_email_confirmation.egg-info
copying simple_email_confirmation/__init__.py -> django-simple-email-confirmation-0.20/simple_email_confirmation
copying simple_email_confirmation/admin.py -> django-simple-email-confirmation-0.20/simple_email_confirmation
copying simple_email_confirmation/exceptions.py -> django-simple-email-confirmation-0.20/simple_email_confirmation
copying simple_email_confirmation/models.py -> django-simple-email-confirmation-0.20/simple_email_confirmation
copying simple_email_confirmation/signals.py -> django-simple-email-confirmation-0.20/simple_email_confirmation
copying simple_email_confirmation/migrations/0001_initial.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/migrations
copying simple_email_confirmation/migrations/__init__.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/migrations
copying simple_email_confirmation/south_migrations/0001_initial.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/south_migrations
copying simple_email_confirmation/south_migrations/__init__.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/south_migrations
copying simple_email_confirmation/tests/__init__.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/tests
copying simple_email_confirmation/tests/tests.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/tests
copying simple_email_confirmation/tests/myproject/__init__.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/tests/myproject
copying simple_email_confirmation/tests/myproject/settings.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/tests/myproject
copying simple_email_confirmation/tests/myproject/myapp/__init__.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/tests/myproject/myapp
copying simple_email_confirmation/tests/myproject/myapp/models.py -> django-simple-email-confirmation-0.20/simple_email_confirmation/tests/myproject/myapp
Writing django-simple-email-confirmation-0.20/setup.cfg
Creating tar archive
removing 'django-simple-email-confirmation-0.20' (and everything under it)
running upload
Submitting dist/django-simple-email-confirmation-0.20.tar.gz to https://pypi.python.org/pypi
Upload failed (400): This filename has previously been used, you should use a different version.
error: Upload failed (400): This filename has previously been used, you should use a different version.
```

**EDIT: `0.21` was released and you can install it via pip ! I guess I learned a lesson today about pypi, good !**
