### ISSUE TITLE
Regarding key_length

### ISSUE THREAD

**Issue by pranaysharma** [mfogel/django-simple-email-confirmation#18]
Should the key length be increased from the regular 12 digit to a more bigger number?

def generate_key(self):
        "Generate a new random key and return it"
        # sticking with the django defaults
        return get_random_string(length=30)

**Comment by mfogel** [comment]
It looks like the default `length=12` gives a [71-bit key space](https://github.com/django/django/blob/1.8.5/django/utils/crypto.py#L59), which I guess is a little short. However, it's better than django's default password length - [10 characters](https://github.com/django/django/blob/1.8.5/django/contrib/auth/models.py#L149). So I'm not too concerned.

That being said, pull requests happily entertained for turning this into a setting or a parameter (with a default of 12).
