### ISSUE TITLE
Looks like the badges from pypi.in are not working in the README

### ISSUE THREAD

**Issue by annp89** [mfogel/django-simple-email-confirmation#19]
This is just FYI. On accessing https://github.com/mfogel/django-simple-email-confirmation and after waiting for the README to load, it looks like badges from pypi.in show up as broken links and you'll notice 404 errors in the console.

Relevant issue https://github.com/badges/pypipins/issues/37

Not sure if you want those to be removed or switched out to use _shields.io_ . If you prefer removing them, I'd be happy to open a pull request for that :)

**Comment by mfogel** [comment]
Thanks for the heads up and the pointers! I went ahead and did the switch to shields.io. Going to switch my other projects to it as well...
