### ISSUE TITLE
Confirmation key generating problem

### ISSUE THREAD

**Issue by yeralin** [mfogel/django-simple-email-confirmation#22]
So, I'm using this app in my django project, and I noticed one strange thing.

When I create a user using form.

```
    if request.method == 'POST' and 'email' in request.POST:

            args['form'] = EmployeeCreationForm()

            form = EmployeeCreationForm(request.POST)

            if form.is_valid():

                    user = form.save()
```

And I try to access: `user.confirmation_key`
Sometimes I get user's confirmation key, or I can get EmaillAdress DoesNotExist exception. 
It doesn't depend on any code. I tested it about 10 times, it happens on random.
So, I came up with this code:

```
    try:    

            confirmation_key = user.confirmation_key

            msg_html = render_to_string('email/confirmation.html', {'key' : confirmation_key})

            return send_mail('Confirmation email', 'whatever@gmail.com', [user.email], html_message=msg_html,
    )
        except:
            confirmation_key = user.add_unconfirmed_email(user.email)

            msg_html = render_to_string('email/confirmation.html', {'key' : confirmation_key})

            return send_mail('Confirmation email', 'whatever@gmail.com', [user.email], html_message=msg_html,
    )
```

So, I try to access user.confirmation_key, if I catch DoesNotExist, I create it manually.

Of course, it shouldn't work that way.

Any thoughts?
I believe it is a problem with signals (they can't reach on time or something)

Django version 1.8.2

Also, here is some messages from my terminal:
simple_email_confirmation/models.py:203: RemovedInDjango19Warning: Model class simple_email_confirmation.models.EmailAddress doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class EmailAddress(models.Model):

simple_email_confirmation/models.py:203: RemovedInDjango19Warning: Model class simple_email_confirmation.models.EmailAddress doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.
  class EmailAddress(models.Model):

**Comment by mdamien** [comment]
Thanks, the 1.9 warnings have been fixed. Does #7 fixes the signal issue ?
