### ISSUE TITLE
ownership transfer

### ISSUE THREAD

**Issue by g-as** [mfogel/django-simple-email-confirmation#23]
As per @mfogel's commit, I was thinking of Jazzband ([github](https://github.com/jazzband), [website](https://jazzband.co/)), which has been designed for this particular case. I believe this project definitely falls into the scope of the [guidelines](https://jazzband.co/about/guidelines), minus a few tweaks. What do you guys think?

**Comment by mfogel** [comment]
Good idea! Actually, @mdamien emailed me with that exact same plan. He volunteered to oversee the transfer. I've added him as an owner on PYPI... I believe he will handle the process from here.

I'm updating the README and the other issue thread with this info now.

**Comment by g-as** [comment]
That's good news. Thanks for your help making sure this project won't go down the drain!

**Comment by mdamien** [comment]
hi @mfogel , it would be easier if I had the owner right of this github repository. Then I can tranfer the issues and the PRs at the same time ( to my account or to jazzband ).

**Comment by mfogel** [comment]
@mdamien it looks like to transfer the repository to you you'll need to delete your fork of it first (https://help.github.com/articles/about-repository-transfers/). Or I can transfer it directly to jazzband. Whichever you prefer.

I added you as a collaborator just now but I think that won't give you all the permissions you're looking for.

**Comment by mdamien** [comment]
I think the best is to keep the repo here while waiting for the transfer to jazzband. Gonna just commit here in the mean time.
