### ISSUE TITLE
Make migration error (Django 2.0)

### ISSUE THREAD

**Issue by yueyes** [mfogel/django-simple-email-confirmation#47]
I am trying to use django-simple-email-confirmation in my django project and install by pip, when I use it and trying to make migration, the following is happended:

"path\simple_email_confirmation\models.py", line 217, in EmailAddress
    settings.AUTH_USER_MODEL, related_name='email_address_set',
TypeError: __init__() missing 1 required positional argument: 'on_delete'

And I fixed it by adding on_delete=models.CASCADE in simple_email_confirmation\models.py, Django 2.0 seems need to add it.

**Comment by mdamien** [comment]
Hi, it’s been fixed on master, thanks for your report, gonna publish it to PyPi
