### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by lehins** [mfogel/django-simple-email-confirmation#5]
In EmailAddress's [unicode](https://github.com/mfogel/django-simple-email-confirmation/blob/develop/simple_email_confirmation/models.py#L173) instead of `return '{} ({})'.format(self.email, self.user)` return `return '{} <{}>'.format(self.user, self.email)` which would result in a value `u"Full Name <email@address.com>"` that can be used as an email parameter to `send_email`.
It's just a suggestion, it would be beneficial to some, I think.

**Comment by lehins** [comment]
Also I saw this [TODO](post_save.connect%28auto_add, sender=EmailAddress.user.field.rel.to%29) and this maybe a solution to it: `post_save.connect(auto_add, sender=EmailAddress.user.field.rel.to)` try it out, I might be wrong though, I just don't have time now to try it myself.

**Comment by mfogel** [comment]
Thanks for the suggestions, I just implemented the first one.
