### ISSUE TITLE
Specify custom EmailAddress model

### ISSUE THREAD

**Issue by ferndot** [mfogel/django-simple-email-confirmation#50]
It would be nice to be able to override the default EmailAddress model. In my case, I would like to use UUID PKs instead of the default AutoField.

Others might want to attach additional fields to the model.

**Comment by jakeharding** [comment]
Hi @joshua-s, 

I'm curious if you are looking into this or if you know of anyone who is?

**Comment by ferndot** [comment]
Hey @jakeharding! I am willing to implement this if there is interest. PR coming soon!
