### ISSUE TITLE
'User' object has no attribute 'is_confirmed'

### ISSUE THREAD

**Issue by metemaddar** [mfogel/django-simple-email-confirmation#56]
Hello,
I use Django 2.1.3, and django-simple-email-confirmation 0.23

When I want to check if request.user is confirmed or not, I get the error:
**'User' object has no attribute 'is_confirmed'**

code:
`if request.user.is_confirmed:`

**Comment by mdamien** [comment]
Have you used the `SimpleEmailConfirmationUserMixin` mixin on you use model ? Like in this example

```
from django.contrib.auth.models import AbstractUser
from simple_email_confirmation.models import SimpleEmailConfirmationUserMixin

class User(SimpleEmailConfirmationUserMixin, AbstractUser):
    pass
```

Also, your have to set `AUTH_USER_MODEL = "your_app.User"` in your `settings.py`

**Comment by ferndot** [comment]
@metemaddar did that resolve the issue for you?

**Comment by ferndot** [comment]
I am closing this because we have heard nothing back (and the thumbs up reaction on mdamien's post seems to indicate that the issue may be fixed). Please comment if this assumption is incorrect.
