### ISSUE TITLE
Upgrade the pip version

### ISSUE THREAD

**Issue by poor-man** [mfogel/django-simple-email-confirmation#64]
Hello

I realized that the version of the code you install directly from pip is the 0.23, when the last version of the code you have here is the 0.6, with significant changes.

Is there any plans to upgrade the pip version? what about the 1.0 version you mention at the end of the documentation?

Thanks.

**Comment by mdamien** [comment]
Thanks, I messed up, I published 0.6 but 0.6 < 0.23 in semantic versioning. Gonna re-release as 0.60 :+1:

**Comment by mdamien** [comment]
@poor-man 0.60 is now published (it's 0.6 re-published as 0.60 since the most recent changes should go in 1.0), thanks for reporting

EDIT: @joshua-s 0.60 is published from the branch `re-release-as-0.60` (just branched from the `release 0.6` commit)

**Comment by ferndot** [comment]
Thanks @mdamien
