### ISSUE TITLE
It would be good to have a pypi build compatible with Django >= 4, pls verify PR72

### ISSUE THREAD

**Issue by feroda** [mfogel/django-simple-email-confirmation#73]
https://github.com/mfogel/django-simple-email-confirmation/pull/72

I use my fork in 2 Django 4 projects.

**Comment by edmenendez** [comment]
I also use your fork in Django 4 projects 🙏

**Comment by joshowen** [comment]
@mfogel any chance you're able to create a pypi release now that the code supporting Django4 has been merged?

**Comment by mfogel** [comment]
I just pushed a new release to pypi... version `0.71` hopefully it works 🤞 . Let me know how it goes.

**Comment by mfogel** [comment]
Optimistically closing
