### ISSUE TITLE
Need to update migrations for Django 1.7

### ISSUE THREAD

**Issue by jeffbowen** [mfogel/django-simple-email-confirmation#9]
Need to update migrations for Django 1.7.
https://docs.djangoproject.com/en/dev/topics/migrations/#libraries-third-party-apps

**Comment by mfogel** [comment]
Merged in that PR. I'll release a new version to pypi that includes this support once I have a chance to do some further use and testing of that change in the field.

**Comment by jeffbowen** [comment]
Thanks!
